### ISSUE TITLE
Not working in angular 18

### ISSUE THREAD

**Issue by voidless-03** [KroneCorylus/ngx-colors#118]
Getting this error in Angular 18

`11:50:17 AM [vite] error while updating dependencies:
Error: ENOENT: no such file or directory, open 'C:\Users\sshourov\Documents\GitHub\voidless\webui\node_modules\ngx-cookie-service\fesm2022\ngx-cookie-service.mjs'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1249:14)
    at async extractExportsData (file:///C:/Users/sshourov/Documents/GitHub/voidless/webui/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:53029:26)
    at async file:///C:/Users/sshourov/Documents/GitHub/voidless/webui/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:52766:29 (x5)
`

**Comment by KroneCorylus** [comment]
Doesn't look like an error of ngx-colors.

**Comment by voidless-03** [comment]
I get the error every time I import the colour module to one of my components. Is importing different for angular 18?

**Comment by KroneCorylus** [comment]
No, importing should work fine in Angular 18. The error you've provided doesn't seem to indicate an issue with ngx-colors. In fact, it points to the ngx-cookie-service package, which suggests that the problem might be related to Vite or how your packages are configured. Unfortunately, I'm not too familiar with Vite.
