### ISSUE TITLE
Does not work inside MatDialog

### ISSUE THREAD

**Issue by Ben555555** [KroneCorylus/ngx-colors#70]
When using the color picker inside a MatDialog:
<ngx-colors ngx-colors-trigger style="display: inline-block; margin:5px;"
                  [formControl]="selectedColorControl" matSuffix acceptLabel="{{ 'Common.Accept' | translate }}"
                  cancelLabel="{{ 'Common.Cancel' | translate }}"></ngx-colors>

The following errors appear:
NullInjectorError: R3InjectorError(AppModule)[PanelFactoryService -> PanelFactoryService -> PanelFactoryService]: 
  NullInjectorError: No provider for PanelFactoryService!
    at NullInjector.get (core.mjs:6368:27)
    at R3Injector.get (core.mjs:6795:33)
    at R3Injector.get (core.mjs:6795:33)
    at R3Injector.get (core.mjs:6795:33)
    at ChainedInjector.get (core.mjs:13866:36)
    at lookupTokenUsingModuleInjector (core.mjs:3290:39)
    at getOrCreateInjectable (core.mjs:3335:12)
    at Module.ɵɵdirectiveInject (core.mjs:10881:12)
    at NodeInjectorFactory.NgxColorsTriggerDirective_Factory [as factory] (ngx-colors.mjs:1093:1)
    at getNodeInjectable (core.mjs:3520:44)
global-error-handler.ts:18 TypeError: Cannot read properties of undefined (reading 'focusInitialElementWhenReady')
    at MatDialogContainer._trapFocus (dialog.mjs:230:33)
    at MatDialogContainer._openAnimationDone (dialog.mjs:142:18)
    at MatDialogContainer._onAnimationDone (dialog.mjs:173:18)
    at MatDialogContainer_animation_dialogContainer_done_HostBindingHandler (dialog.mjs:206:100)
    at executeListenerWithErrorHandling (core.mjs:15776:16)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:15811:22)
    at animations.mjs:187:34
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26376:33)
    at _ZoneDelegate.invoke (zone.js:371:52)

**Comment by Ben555555** [comment]
My fault. The dialog was opened from another Module which didn't import the color picker. This issue can be closed.
